use skia_safe::{Canvas, Color, Paint, PathBuilder, Point};
pub fn draw_music_icon(canvas: &Canvas, cx: f32, cy: f32, alpha: u8, scale: f32) {
    let mut paint = Paint::default();
    paint.set_anti_alias(true);
    paint.set_color(Color::from_argb(alpha, 255, 255, 255));
    paint.set_style(skia_safe::paint::Style::Fill);
    let head_r = 3.5 * scale;
    let left_head = Point::new(cx - 5.0 * scale, cy + 6.0 * scale);
    let right_head = Point::new(cx + 5.0 * scale, cy + 3.0 * scale);
    canvas.draw_circle(left_head, head_r, &paint);
    canvas.draw_circle(right_head, head_r, &paint);
    let mut builder = PathBuilder::new();
    let stem_width = 1.8 * scale;
    builder.move_to(Point::new(cx + (head_r - stem_width - 5.0 * scale), cy - 9.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r - stem_width + 5.0 * scale), cy - 12.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r + 5.0 * scale), cy - 12.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r + 5.0 * scale), cy + 3.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r - stem_width + 5.0 * scale), cy + 3.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r - stem_width + 5.0 * scale), cy - 9.5 * scale)); 
    builder.line_to(Point::new(cx + (head_r - stem_width - 5.0 * scale), cy - 6.5 * scale)); 
    builder.line_to(Point::new(cx + (head_r - stem_width - 5.0 * scale), cy + 6.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r - 2.0 * stem_width - 5.0 * scale), cy + 6.0 * scale)); 
    builder.line_to(Point::new(cx + (head_r - 2.0 * stem_width - 5.0 * scale), cy - 9.0 * scale)); 
    builder.close();
    let path = builder.detach();
    canvas.draw_path(&path, &paint);
    let mut beam_builder = PathBuilder::new();
    let beam_h = 4.0 * scale;
    beam_builder.move_to(Point::new(cx + (head_r - 2.0 * stem_width - 5.0 * scale), cy - 9.0 * scale));
    beam_builder.line_to(Point::new(cx + (head_r + 5.0 * scale), cy - 12.0 * scale));
    beam_builder.line_to(Point::new(cx + (head_r + 5.0 * scale), cy - 12.0 * scale + beam_h));
    beam_builder.line_to(Point::new(cx + (head_r - 2.0 * stem_width - 5.0 * scale), cy - 9.0 * scale + beam_h));
    beam_builder.close();
    canvas.draw_path(&beam_builder.detach(), &paint);
}
